apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: finalproject-dev   # 원하는 네임스페이스
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dockerhubID/finalproject-backend:latest   # 실제 이미지 경로
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"    # 필요 시 환경변수 추가
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: finalproject-dev
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080        # 서비스 포트
      targetPort: 8080  # 컨테이너 포트
  type: ClusterIP       # 외부 접근 필요하면 NodePort 로 변경

