apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-backend
  namespace: finalproject-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-backend
  template:
    metadata:
      labels:
        app: shop-backend
    spec:
      containers:
        - name: backend
          image: fk36dks/shop-backend:latest
          ports:
            - containerPort: 5000   # 8080 대신 5000

