apiVersion: v1
kind: Service
metadata:
  name: shop-frontend
  namespace: finalproject-dev   # ✅ namespace 수정
spec:
  type: NodePort                # 외부에서 접근해야 하면 유지
  selector:
    app: shop-frontend
  ports:
    - port: 80
      targetPort: 80

