apiVersion: v1
kind: Service
metadata:
  name: shop-frontend
  namespace: default
spec:
  type: NodePort
  selector:
    app: shop-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

