apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finalproject-dev
resources:
- deployment.yaml
- service.yaml
images:
- name: docker.io/fk36dks/finalproject
  newTag: 1.0-28-bba42a1
